### PR TITLE
Feat: Add prettier config

### LINKED ISSUE #17: Add prettier for code formatting.
Create a prettier formatting rules for the project, [reference](https://prettier.io/docs/en/configuration).

make sure the the indent size is `4`, and that strings use double qoutes, everything else doesn't really matter.

### PR DESCRIPTION
**Pull request by Dimah02**
I formatted all .svelte files but I could not run the format command on .css and .ts files for an unknown error.

### CODE REVIEW

**Comment by mbaraa** [comment]
@Dimah02  can you share the format error in a comment?

**Comment by Dimah02** [comment]
@mbaraa 
when running 
`npx prettier --write src/lib/models/Event.ts`
```
src/lib/models/Event.ts
[error] src/lib/models/Event.ts: Expected }   
[error]   1 | export default interface Event {
[error] > 2 |     name: string;
[error]     |        ^
[error]   3 |     description: string;
[error]   4 |     link: string;
[error]   5 |     imagePath: string; (2:8)
[error] 1: export default interface Event {
[error] 2:     name: string;
[error]            ^
[error] 3:     description: string;
[error] 4:     link: string;
```
Event.ts code
```
export default interface Event {
    name: string;
    description: string;
    link: string;
    imagePath: string;
    altImagePath: string;
}
```

**Comment by mbaraa** [comment]
> @mbaraa when running `npx prettier --write src/lib/models/Event.ts`
> 
> ```
> src/lib/models/Event.ts
> [error] src/lib/models/Event.ts: Expected }   
> [error]   1 | export default interface Event {
> [error] > 2 |     name: string;
> [error]     |        ^
> [error]   3 |     description: string;
> [error]   4 |     link: string;
> [error]   5 |     imagePath: string; (2:8)
> [error] 1: export default interface Event {
> [error] 2:     name: string;
> [error]            ^
> [error] 3:     description: string;
> [error] 4:     link: string;
> ```
> 
> Event.ts code
> 
> ```
> export default interface Event {
>     name: string;
>     description: string;
>     link: string;
>     imagePath: string;
>     altImagePath: string;
> }
> ```

change `.prettierrc`'s content to:
```json
{
	"useTabs": true,
	"tabWidth": 4,
	"singleQuote": false,
	"semi": true,
	"trailingComma": "all",
	"printWidth": 80,
	"plugins": ["prettier-plugin-svelte"],
	"overrides": [
		{
			"files": ["*.svelte"],
			"options": {
				"parser": "svelte"
			}
		}
	]
}
```

**Comment by mbaraa** [comment]
@Dimah02 don't close pull requests unless they're done.

**Review by mbaraa — APPROVED** [review]
good job!

**Pull request merged**
